### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by RabertD** [paypal/paypalcheckout-ios#106]
### 🐞 Describe the Bug
Paypal SDK page automatically dismissed at very first time. The problem happened only in read device. 

### 🔬 Minimal Reproduction
Check very first time. I added the video reference for that

### 😕 Actual Behavior
Paypal SDK page automatically dismissed at very first time.

### 🤔 Expected Behavior
Its should fetch the added cards and make the payment successful. 

### 🌍 Environment

- iOS version: - 15.5
- SDK version (`Checkout.version`): - 0.94.0

https://user-images.githubusercontent.com/107385984/177690679-cb246bac-4464-42e5-a772-0eb0fa87accd.MP4

**Comment by jonathajones** [comment]
Hi @RabertD - 
There are several things that contribute to the end user being eligible for the native paysheet experience. if a user is ineligible for the native flow for any reason (for example, buyer location, or transaction risk might trigger an ineligibility response), the user is presented with a web flow instead of the native one. It seems like the flow here was successful, but was handled through the web fallback - were the `onApprove` or `onError` callbacks invoked?

**Comment by jonathajones** [comment]
Closing, as it's a stale issue.
