### ISSUE TITLE
[🐞] All Web fallback UI with onApproval Callback not sending cart info

### ISSUE THREAD

**Issue by mpalanisamy-pkglobal** [paypal/paypalcheckout-ios#135]
### 🐞 Describe the Bug
@jonathajones  If we choose the PayIn4 payment option or the regular web fallback UI  in the Paypal SDK and continue with the wallet balance/card/split option in the payment then complete the order action the onApprove callback not sending cart info.

### 🔬 Minimal Reproduction
Go to PayPal checkout --> select PayIn4 payment Method --> select any payment option(SDK web UI) --> complete order--> order failing due to no cart info on the onApprove callback. 

### 😕 Actual Behavior
From the payPal SDK web UI if we complete the payment order onApprove Callback is not sending the cart information. The cart object is nil.

### 🤔 Expected Behavior
From the payPal SDK web UI if we complete the payment order onApprove Callback should return the cart information. The cart object should not be nil.

### 🌍 Environment

- iOS version: All iOS device and Versions-
- SDK version (`Checkout.version`):  v0.110.0

**Comment by jonathajones** [comment]
Hi @mpalanisamy-pkglobal - This is expected behavior, that I outline here : https://github.com/paypal/paypalcheckout-ios/issues/133#issuecomment-1425079064

If you need cart data and it does not exist in the approval response, then you need to make a request to get the details of the cart. You can do this either using the `getOrderDetails` order action within the SDK, or by using the orders REST api (https://developer.paypal.com/docs/api/orders/v2/#orders_get)

**Comment by jonathajones** [comment]
We will make a documentation update, or potentially remove the cart object from the approval response altogether to avoid this inconsistency

**Comment by mpalanisamy-concentrix** [comment]
@jonathajones  thank you for the response. we will use "getOrderDetails" for the cart information as I mentioned in the #133 the phone number object is missing in the iOS SDK.

**Comment by jonathajones** [comment]
Closed as this has been resolved
