### ISSUE TITLE
📙 Documentation Issue Report

### ISSUE THREAD

**Issue by doktorlorenzo** [paypal/paypalcheckout-ios#150]
### 📙 Describe the Issue
Unclear what is the currently suggested framework to integrate native paypal payments for production

### 🔬 Minimal Reproduction
In the main readme there is the following disclaimer: https://github.com/paypal/paypalcheckout-ios
> This integration path is only active for existing developers who have previously integrated the PayPal iOS Checkout SDK. For any new developers seeking the Native Checkout experience, **this integration path is considered inactive**. Please integrate via BrainTree iOS SDK or PayPal iOS SDK.

But then the ones which is recommended, https://github.com/paypal/iOS-SDK/ , says:
> The SDK is currently in the development process. This product is being developed fully open source - throughout the development process, we welcome any and all feedback. Aspects of the SDK will likely change as we develop the SDK. **We recommend using the SDK in the sandbox environment** until an official release is available. This README will be updated with an official release date once it is generally available.

For an app that is going to hit production in a few days/weeks, what is the recommended way? I consider `paypalcheckout-ios
` to be the safe choice, also the one that is referred the most on the [official docs](https://developer.paypal.com/limited-release/paypal-mobile-checkout/ios/ ) and still in Beta. But i would like confirmations, especially since the integration  of `iOS-SDK` was for us unsuccessful and more complicated when factoring in "server-side integration"

### ➕ Additional Context
Sorry, i am not sure where to report this. Thanks for your time.

**Comment by rajulparekh01** [comment]
Hi! Thank you for reaching out to our team. Unfortunately this integration path will no longer be supported in the near future, so we encourage all new merchants to integrate via BrainTree iOS SDK or PayPal iOS SDK. Can you elaborate on what issues you faced when integrating iOS-SDK?

**Comment by rajulparekh01** [comment]
Thanks for the feedback, it's very helpful! We'll relay this to the PayPal SDK team and work closely with them to improve the documentation.

**Comment by stechiu** [comment]
@doktorlorenzo Apologies for the confusion. The README has been updated with the latest info. As @rajulparekh01 mentioned, you can use the PayPal Checkout SDK via https://github.com/braintree/braintree_ios or https://github.com/paypal/iOS-SDK/. If you tried to integrate using https://github.com/paypal/PayPal-iOS-SDK, that repo has been archived since 2020 so it's not up-to-date

If you continue to experience issues integrating the SDK via Braintree or paypal/iOS-SDK, you can raise the issue here https://github.com/braintree/braintree_ios/issues or contact Braintree support support@braintreepayments.com
