### ISSUE TITLE
Invalid Scope

### ISSUE THREAD

**Issue by jkblgithub** [paypal/paypalcheckout-ios#23]
Hi, 

We are trying to test a sandbox transaction. We use your REST API to generate an order_id server side, which we then use to launch the checkout as follows:

```
PYPLCheckout* checkout = [PYPLCheckout sharedInstance];
checkout.serviceEnvironment = kPYPLEnvironment_SandBox;
 [checkout startCheckoutWithECToken:@"3VB96611PE542521D" withDelegate: self];
```

Unfortunately, we get the screen as per the attached image. Could you please advise as to the possible cause?

Kind regards,

Juan

![Simulator Screen Shot - iPhone Xʀ - 2019-07-12 at 10 32 22](https://user-images.githubusercontent.com/8487967/61114477-af9c1b00-a490-11e9-84ba-27cb6f73c8a1.png)

**Comment by fbarraganef** [comment]
I have the same issue and I don't have any idea the reason, why is happening.

**Comment by jkblgithub** [comment]
I think this lib is no longer supported. Use the paypal/braintree express checkout instead : https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/

**Comment by fbarraganef** [comment]
I can't use it, because the app where I have to integrate is in Mexico and Braintree is not available for that country.

**Comment by jkblgithub** [comment]
You dont need a braintree account to use it, just paypal. It’s all in the docs i linked

**Comment by fbarraganef** [comment]
I will need to implement extra functionality from my server side, right?  because I'm using version 2 (/orders and /payments)from PayPal API, and Braintree is requesting me a clientTokenOrTokenizationKey , If I am creating a order with: 
https://developer.paypal.com/docs/api/orders/v2/

I will need create the order using Braintree server SDK again and get the client token and proceed to process the payment using Braintree. 

Thanks,

**Comment by jkblgithub** [comment]
Yes, you will need to get a token from braintree at the start of every session. We dont use orders, we simply do a transaction.sale on the server after the user got a nonce in the app after completing the paypal payment details.
