### ISSUE TITLE
Could not find module 'PayPalCheckout' for target 'armv7-apple-ios'; 

### ISSUE THREAD

**Issue by Dharini17** [paypal/paypalcheckout-ios#65]
### Describe Your Issue
I've used PayPalCheckout framework by downloading from below link,
https://github.com/paypal/paypalcheckout-ios/releases/tag/0.66.0
Xcode 12.4 , Swift 5 , ios 12.1 

while running on device it successfully build but when I tried to upload on release time it gives below message,

Could not find module 'PayPalCheckout' for target 'armv7-apple-ios'; found: arm64-apple-ios, arm64, x86_64-apple-ios-simulator, x86_64

**Comment by jaxdesmarais** [comment]
Hello @Dharini17 -

Can you confirm the `deployment_target` you are using for your app? It will need to be at a minimum `11.0` and would be set in your project targets deployment info. That error message typically indicates that you are attempting to release for devices with a lower deployment target than our SDK supports.

**Comment by Dharini17** [comment]
I've used 11.0 deployment target, can you please suggest me which version supports with 11.0 ios version

**Comment by Dharini17** [comment]
Yeah its done but now I getting Code signing "PayPalCheckout.framework" failed while uploading

**Comment by jaxdesmarais** [comment]
Hello @Dharini17 -

I was able to find a few StackOverflow issues that addressed a similar error [here](https://stackoverflow.com/questions/53050451/xcode-10-code-signing-my-appframework-fails-because-of-failure-signing-3rd-pa), [here](https://stackoverflow.com/questions/68151063/internal-error-in-code-signing-subsystem-xcode-12) and [here](https://stackoverflow.com/questions/41476565/ios-test-flight-error-due-to-code-signing-issue). As this error is related to your configuration within Xcode and not the SDK, our support is fairly limited as there are many contributing factors to how your app is configured within Xcode and set up to be distributed.

**Comment by Dharini17** [comment]
Thanks it's done now

**Comment by jaxdesmarais** [comment]
Thanks for the update @Dharini17, I'll close out this issue.
