### ISSUE TITLE
[🐞] Bug Report

### ISSUE THREAD

**Issue by for-meng** [paypal/paypalcheckout-ios#80]
### 🐞 Describe the Bug
After canceling, I called up Paypal again, and two pages appeared, one is the login page and the other is the logged-in page

https://user-images.githubusercontent.com/16735123/141456062-b37d68dc-6f3b-4941-9717-6cfb53883f40.mp4

**Comment by jaxdesmarais** [comment]
Hello @for-meng -

Would you mind sharing the follow details as I have not been able to replicate this error on the latest version of the SDK:
- SDK version
- Device and iOS version being used
- If there are any errors being emitted in the `onError` callback

**Comment by for-meng** [comment]
SDK version  0.77
Simulator iPhone XR  14.5
onError has nothing log 
sometimes it also appears directly without cancel operation
it look like the sdk  has logic error when  deal with the login status

**Comment by for-meng** [comment]
or you can try do this:
1. checkoutSDK start
2. click other place to cancel it  before it appear 
![image](https://user-images.githubusercontent.com/16735123/143411025-2f651931-d70a-44c3-89ee-676823ec69a4.png)
3. restart checkoutSDK

**Comment by jaxdesmarais** [comment]
Hello @for-meng -

I've done some additional digging into this and been able to replicate this error - thanks for providing the steps you've followed to replicate this. We are working internally with the team that owns the authentication portion of the SDK (where this bug is manifesting from) to resolve this issue. Once we have further details on when a resolution will be deployed and subsequently picked up by our SDK, I will provide an update for you here.

**Comment by jonathajones** [comment]
Hi @for-meng  - 
This should be resolved in the latest release (0.94.0). Please test and let us know if you have any other questions.
